### ISSUE TITLE
Purpose of Schema

### ISSUE THREAD

**Issue by RobertGardner** [historical-data/schema#1]
I think it's important to emphasize that the primary purpose of this schema is for Web Search Engine Optimization (SEO). It would be nice if it can also be used for other purposes, such as automated site scraping to retrieve genealogical information for research purposes, but that should not detract from the primary purpose of making genealogical information on the web easier for search engines to recognize and index.

**Comment by stoicflame** [comment]
+1

**Comment by stoicflame** [comment]
Assuming everybody is agreed, I'll add some language to the index page and send a pull request.

**Comment by clarkegj** [comment]
+1 also.  I'm finding my way around GitHub

-"Flash" Gordon

**Comment by stoicflame** [comment]
I've created the pull request at #5. Closing this issue as a duplicate.
