### ISSUE TITLE
create presentation for rootstech 2012

### ISSUE THREAD

**Issue by stoicflame** [historical-data/schema#15]
I think @ninjudd should create and propose a presentation for RootsTech 2012.

**Comment by RobertGardner** [comment]
The proposal deadline has passed but he may still be able to get in.

I proposed a talk titled "Optimizing Your Site for Search Engines" which was accepted. I was planning on mentioning this proposal in that talk without going into much detail. If Justin gets a talk approved he can go over the details -- he'd be much, much more qualified for that than I would. If he doesn't, I can go into more detail in my talk.

**Comment by stoicflame** [comment]
> The proposal deadline has passed but he may still be able to get in.

I bet we can get him in if he's willing.

**Comment by ninjudd** [comment]
I'm already giving a talk on our Graph backend, but I'd be happy to give another presentation about historical-data.org.

**Comment by davebarney** [comment]
This is already part of one of the talks we will be giving from Google. I personally think a micro-data format would be better received in the industry if presented by Google. Also, we will be talking about this micro-format as part of a larger talk on how content providers can make their data more accessible on the web, so it fits inline with the topic.

**Comment by stoicflame** [comment]
So you're saying that we don't need this preso because you'll already cover it in your preso?

That's fine with me. If everybody else is agreed, I'll close the issue.

**Comment by davebarney** [comment]
Yes

**Comment by ninjudd** [comment]
Agreed. I think you're right about better acceptance if presented by Google.
