### ISSUE TITLE
Legal Gender Values?

### ISSUE THREAD

**Issue by RobertGardner** [historical-data/schema#17]
Schema.org provides a "gender" field in Person but does not specify legal values. I think we should document values we consider legal in a HistoricalPerson. Alternatively, since "gender" is now considered a "preference" by some, we could add a "sex" field which has unambiguous values.

**Comment by ninjudd** [comment]
I vote for sticking with `gender` and specifying `male` and `female` as valid values.

**Comment by NatAtGeni** [comment]
I like `gender` and having `male`, `female` and `unknown` as values.

**Comment by stoicflame** [comment]
> I like gender and having male, female and unknown as values.

sounds good to me.

**Comment by RobertGardner** [comment]
LGTM

**Comment by NatAtGeni** [comment]
> LGTM

I suspect this is why the `Person` spec didn't specify values - just said `Text` and left it at that.

**Comment by RobertGardner** [comment]
Oh, sorry, "LGTM" is a common Google abbreviation that means "Looks Good To Me". I'm on a readability team that vets new engineers to ensure their code is readable and we mark the reviews LGTM when we're happy. We had some t-shirts made up with a big red "LGTM" blazoned on the back as a gift to the reviewers. One of the reviewer's kids asked him if it was some new lesbian/gay/something acronym. Now I can't wear the shirt anymore! :-)

**Comment by stoicflame** [comment]
fixed at c3a73a0
