### ISSUE TITLE
Who is the creator of the historical-data schema?

### ISSUE THREAD

**Issue by todrobbins** [historical-data/schema#27]
Hi,

I'm new to the project, but wanted to get a little more info about the origins of the schema. I'm a current MLIS student up at the University of Washington and I've been working on metadata research and RDF application profile development for cultural heritage works. I'm curious where the impetus for the project came from, what's the status, etc.

Cheers!

PS: Sorry to add a non-issue ;-)

**Comment by todrobbins** [comment]
Also, my apologies for not looking back to the first issues. I have a better idea now what's going on. Another quick question, is the FamilySearch fork a spinoff or a collaboration?

**Comment by stoicflame** [comment]
> is the FamilySearch fork a spinoff or a collaboration?

Collaboration.

If you're interested in RDF application development and semantic analysis, you may also want to check out [GEDCOM X](http://www.gedcomx.org/), which defines RDF schema documents and has [built-in support for RDF integration](http://www.gedcomx.org/RDF-Integration.html) from inception.

**Comment by todrobbins** [comment]
Great! Thanks for the clarification. Sorry I missed your presentation today! I was at RootsTech last year in the unconference session on data standards with Gordon and others. So happy to see the process moving forward.
