### ISSUE TITLE
Newby Finds Inconsistencies

### ISSUE THREAD

**Issue by ghost** [historical-data/schema#29]
Friends, as a new collaborator to this project, I have perused the schema and have come up with some observations. Since I'm new, I am hesitant to classify any of these as bugs and am soliciting your guidance in that determination. Here's the list.

Mike

In all four schema entities:
- url: has expected type of 'Text'. Shouldn't this be 'URL'? It is 'URL' for the 'url' field of 'Thing'.
- modifiedDate: This seems pretty generic. Should we push to have 'modifiedDate' moved up to 'Thing'?
- modifiedDate: We have this property but there is no 'modifiedBy' property. Is that intended?
  [I'd kind of like to see a list of 'modifications' with date, by whom, and description. That way a search could say: find the mike birth that fred changed last year.]

HistoricalRecord:
- locations: has expected type of 'Date'. Shouldn't this be 'Text' or something else?
- note: What is the 'note' property for? Seems redundant with 'description'. Or, if it's generic enough, it ought to be part of 'Thing'.

HistoricalPerson:
- spouses: Should this have a comment "(Replaces Person spouse)"?

Country:
- Countries come and go. Is the top-level 'Country' adequate for describing a country that no longer exists? Is there a need for 'HistoricalCountry', 'HistoricalAdministrativeArea' or even 'HistoricalPlace'?

**Comment by tonyruscoe** [comment]
In all four schema entities:
• url: I agree that this should always have an expected type of “URL”

HistoricalRecord:
• locations: This should probably be “Place or PostalAddress” like HistoricalEvent locations
• note: While notes could be added to all entities, it seems more common to have notes against records

HistoricalPerson:
• spouses: Technically it doesn’t replace the spouse property, but perhaps a recommendation that it should be used instead of spouse would be good.

Country: The expect type (schema.org/Country) offers a geo property that lets you specify coordinates. I guess that means you could provide different country names for the same coordinates. I’m not sure how HistoricalPlace would differ to this. Any suggestions?

**Comment by ghost** [comment]
I'm OOO this week while visiting the Design West conference in San Jose.
Friday I will be on-campus hosting a referral for lunch who would like to
add @google.com to the end of his email address. So I will be unable to do
anything about this for a while.

I also suppose I should have joined the historical-data.org with my @google
email.

Mike

On Mon, Mar 26, 2012 at 2:08 PM, Tony Ruscoe <
reply@reply.github.com

> wrote:
> 
> In all four schema entities:
>  url: I agree that this should always have an expected type of URL
> 
> HistoricalRecord:
>  locations: This should probably be Place or PostalAddress like
> HistoricalEvent locations
>  note: While notes could be added to all entities, it seems more common
> to have notes against records
> 
> HistoricalPerson:
>  spouses: Technically it doesnt replace the spouse property, but perhaps
> a recommendation that it should be used instead of spouse would be good.
> 
> Country: The expect type (schema.org/Country) offers a geo property that
> lets you specify coordinates. I guess that means you could provide
> different country names for the same coordinates. Im not sure how
> HistoricalPlace would differ to this. Any suggestions?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/historical-data/schema/issues/29#issuecomment-4704319

## 

Mike Rossetti
mrossetti@gmail.com

Universal: 801-TRY-MIKE
(801-879-6453)

Cynics do not contribute;
Skeptics do not create;
Doubters do not achieve.
Bryant S. Hinckley
