### ISSUE TITLE
Properties from Person not in HistoricalPerson, maybe should be??

### ISSUE THREAD

**Issue by rongreenwood** [historical-data/schema#30]
I'm new to this project and after reviewing the schema have a question. It seems like there are properties in Person that should be used in HistoricalPerson, but are not as the schema is currently defined. The ones that make the most sense to me are givenName, familyName and additionalName. Is there a reason why these were left out? 

Thanks!

**Comment by davebarney** [comment]
All properties from Person are inherited, so these are available. The point you raise, however, is that this is not clear. We've had similar questions asked before. I think the section "Properties from Person" should include an explanation that all properties from Person are included and then perhaps list a few, as examples, that are particularly relevant for a "historical person".

**Comment by rongreenwood** [comment]
My initial assumption was that all properties from Person were inherited. However, when I saw that awards, gender and nationality were called out in the HistoricalPerson schema as Properties from Person it made it appear that those were the only inherited properties. Clarifying this would be great.

**Comment by davebarney** [comment]
Correct. The documentation is not clear. I will take this as an action item.

**Comment by tonyruscoe** [comment]
A quick check of a few items on schema.org suggests that they always list all of the properties that are being inherited, so listing all inherited properties here would probably be the most transparent solution.

**Comment by davebarney** [comment]
Thanks, Tony! I am in the process of updating the webpages right now to reflect this.

**Comment by davebarney** [comment]
Changes are now live. In the process of adding the missing "inherited" fields, I realized a number of them only make sense to "override" rather than "inherit". For example, "relatedTo", "knows", "spouse", etc.
