### ISSUE TITLE
Rename Person.children to Person.child?

### ISSUE THREAD

**Issue by DallanQ** [historical-data/schema#37]
This may not be possible, since Person.children is defined in Schema and not HistoricalData, but every other relation in Person deprecates the plural form.

**Comment by fleep** [comment]
Is the premise that the singular form of each property is also capable of storing a collection, as well?

**Comment by DallanQ** [comment]
yes.

**Comment by fleep** [comment]
I'm surprised the Schema core folk hadn't deprecated the plural alongside everything else, seems as though it would make the most sense. Maybe it could be a part of an upcoming recommendation anyway, for consistency's sake.

**Comment by RobertGardner** [comment]
@danbri just said he'd add this to the schema.org TODO list.
